### ISSUE TITLE
Cant run install.sh

### ISSUE THREAD

**Issue by TiagoLourinho** [the-raspberry-pi-guy/lcd#17]
Hi!
I found your project on your tutorial (https://www.youtube.com/watch?v=fR5XhHYzUK0&t=281s&ab_channel=TheRaspberryPiGuy) but when i try to use it i get this error, and because i dont really know shell script i dont know what to do... I have  already tried to google the error but everything that i tried didnt work.
Thanks in advance, any help would be greatly appreciated!

![img](https://user-images.githubusercontent.com/60043258/102950192-026d6500-44c2-11eb-9411-3ee2a90a6f69.png)

**Comment by cgomesu** [comment]
try `sudo bash install.sh` or `sudo ./install.sh` instead.  the line reference is a bash regex that `sh` won't understand.

**Comment by TiagoLourinho** [comment]
> try `sudo bash install.sh` or `sudo ./install.sh` instead. the line reference is a bash regex that `sh` won't understand.

Thanks!! The first one worked! Closing the issue!

**Comment by the-raspberry-pi-guy** [comment]
Good work again with helping this issue :))
