### ISSUE TITLE
Flashing cursor

### ISSUE THREAD

**Issue by johnroberts2k** [the-raspberry-pi-guy/lcd#34]
I've got this working. But at the end of my text I always have a flashing cursor. Is there a way to turn that flashing cursor off?

**Comment by cgomesu** [comment]
I'm not entirely sure I understand what you mean by flashing cursor at the end of your text.  Could you please provide an example of it?  Make sure to attach your script to the reply as well.

**Comment by cgomesu** [comment]
author has not followed up after a week.  closing this issue.
