### ISSUE TITLE
turn off the lcd screen

### ISSUE THREAD

**Issue by bob5731** [the-raspberry-pi-guy/lcd#51]
How do I turn off a lcd screen?

**Comment by cgomesu** [comment]
take a look at the backlight control demo

**Comment by bob5731** [comment]
Can I get some example code?

**Comment by cgomesu** [comment]
```Python
import drivers
from time import sleep

display = drivers.Lcd()

#turn the backlight on
display.lcd_backlight(1)
#wait for the backlight to toggle
sleep(0.5)
#turn the backlight off
display.lcd_backlight(0)
```

from [demo_lcd_backlight.py](https://github.com/the-raspberry-pi-guy/lcd/blob/master/demo_lcd_backlight.py)

**Comment by bob5731** [comment]
Package 'python-smbus' has no installation candidate
[LCD] [WARNING] Unable to install pkg 'python-smbus'.

**Comment by bob5731** [comment]
> ```python
> import drivers
> from time import sleep
> 
> display = drivers.Lcd()
> 
> #turn the backlight on
> display.lcd_backlight(1)
> #wait for the backlight to toggle
> sleep(0.5)
> #turn the backlight off
> display.lcd_backlight(0)
> ```
> 
> from [demo_lcd_backlight.py](https://github.com/the-raspberry-pi-guy/lcd/blob/master/demo_lcd_backlight.py)

File "/home/pi/pill-dispenser/test12.py", line 1, in <module>
    import drivers
ModuleNotFoundError: No module n
