### ISSUE TITLE
Cannot run install.sh

### ISSUE THREAD

**Issue by vismodo** [the-raspberry-pi-guy/lcd#56]
**Describe the bug**
Cannot run install.sh

**Executed command and associated error**
```
sudo sh install.sh # i also tried using sudo install.sh
```
```
install.sh: 21: ./setup.sh: Permission denied
```

**Host and software info**
- RPi board version: `Pi 4B`
- OS version: `Raspberry PI OS 64 bit released 2022-09-22`
- (If shell related.) Shell: `GNU bash, version 5.1.4(1)-release (aarch64-unknown-linux-gnu)`

**Checklist**
- [x] I have watched and followed the instructions in the [Youtube tutorial](https://www.youtube.com/watch?v=fR5XhHYzUK0).
- [x] I have searched [open and closed issues](https://github.com/the-raspberry-pi-guy/lcd/issues) for either an identical or similar bug before reporting this new one.

**Additional context**
I have not used the raspberry pi without ssh. The pi has never been setup. I use a Pi 4B and the official 64 bit rpi os.

**Comment by warrence** [comment]
im having the same problem too

**Comment by cgomesu** [comment]
Do you still get permission denied if you try running `setup.sh` with sudo?

```sh
sudo bash setup.sh
```

The only thing that the `install.sh` script does is call `setup.sh`, which actually installs all related packages and enables I2C.

**Comment by bvirg** [comment]
chmod u+x setup.sh

**Comment by cgomesu** [comment]
@vismodo, @warrence: please confirm that @bvirg's suggestion fixes the issue.

**Comment by cgomesu** [comment]
Please update your local repo (`git pull`) and try running the `install.sh` once again.  If the issue persists, let me know.  I will assume it has been fixed for the time being.
