### ISSUE TITLE
Displaying the IP address shows a b' in front of IP address

### ISSUE THREAD

**Issue by Mikes-Git** [the-raspberry-pi-guy/lcd#60]
**Describe the issue**
Displaying the IP Address shows following:
b' 192.168.223.228
how can I get the b' not to be displayed?

Is there a way to display the port as well?

**Demo**
- File: https://github.com/the-raspberry-pi-guy/lcd/blob/master/demo_clock_and_IP.py
- (Optional.) Author: Sierra007117

**Executed command and associated error**
```
python demo_clock_and_IP.py
```
```
shows: b' 192.168.223.228
```

**Host and software info**
- RPi board version: `Pi 4 B`
- OS version: `2032-02-21`
- Python version : `3`

**Checklist**
- [X] I have watched and followed the instructions in the [Youtube tutorial](https://www.youtube.com/watch?v=fR5XhHYzUK0).
- [X] I have searched [open and closed issues](https://github.com/the-raspberry-pi-guy/lcd/issues) for either an identical or similar bug before reporting this new one.
- [ ] I have used Python 2.7

**Additional context**

**Comment by Mikes-Git** [comment]
Fixed by adding `encoding="utf8"` to IP

so

`IP = check_output(["hostname", "-I"], encoding="utf8").split()[0]`

**Comment by cgomesu** [comment]
glad you managed to find an answer on your own.  indeed, the `check_output()` method returns a byte literal (`b''`) or `None` if no encoding is specified.  see the [`subprocess` documentation](https://docs.python.org/3/library/subprocess.html) for additional info.
