### ISSUE TITLE
Omision on README about quotable.io quote length restrictions

### ISSUE THREAD

**Issue by jdarias** [the-raspberry-pi-guy/lcd#64]
**Describe the issue**
I forgot to add info about the quotable.io capability to limit the quote character length in the readme.
This is in regards to the demo file demo_tiny_dashboard.py

**Document**
- File: `README.md`

I am adding this on the pull request for the demo_forex.py fix

**Comment by cgomesu** [comment]
> I am adding this on the pull request for the demo_forex.py fix

hey, @jdarias . let's keep things separated. if you don't mind, please **submit another PR for this change** and link the new PR to this issue by adding `- fix #64` in description.

**Comment by cgomesu** [comment]
stale
