### ISSUE TITLE
Backlight control

### ISSUE THREAD

**Issue by HNJAMeindersma** [the-raspberry-pi-guy/lcd#9]
Is there any backlight control (e.g. on/off) available in your driver?

**Comment by the-raspberry-pi-guy** [comment]
This hasn't been implemented in this repo, but if you add this support please feel free to make a PR and share! Thanks :)

**Comment by HNJAMeindersma** [comment]
If I could, I would.
Possible feature request?

**Comment by the-raspberry-pi-guy** [comment]
Sure, I understand. Unfortunately I do not have the time/resources to spend adding this feature for you - my studies are just about to recommence :)

**Comment by HNJAMeindersma** [comment]
Understandable. Maybe I can splice some libraries together if I can find some.

**Comment by Tomtom0201** [comment]
Check here for backlight control implementation (depending on your LCD hardware):
https://github.com/the-raspberry-pi-guy/lcd/issues/12#issuecomment-710183958
